'use strict';

// api/intelligence/qa-gate.js
// The sole gate between raw Grok output and anything EvidenceOS persists or
// surfaces. Approved design (grok_intelligence_directive checkpoint 1): a
// single forced tool call per batch, kind-specific allowed qa_status sets
// enforced BOTH in the prompt and again in code after the tool call returns
// (sanitiseStatus -- a misbehaving model response can never violate the
// invariant), and fail-closed to NEEDS_REVIEW for every item in the batch
// on any error -- nothing ever defaults to an accepted status on failure.
//
// assembleQaResults is the pure, testable assembly step (mirrors
// api/intelligence/agents/prophet.js#assembleAssessment): it rebuilds each
// result field-by-field from the raw tool input, so a malformed or hostile
// tool response can never smuggle an unexpected field through. runQaGate is
// the thin wrapper that makes the live call, applies a timeout, and falls
// back to a full fail-closed batch on any error.

const Anthropic = require('@anthropic-ai/sdk');
const { agentConfig } = require('./config');

const client = new Anthropic();

const EXTERNAL_ALLOWED_STATUSES = ['VERIFIED', 'QUALIFIED', 'NEEDS_REVIEW', 'REJECTED'];
const INNOVATION_ALLOWED_STATUSES = ['SPECULATIVE', 'NEEDS_REVIEW', 'REJECTED'];
const QA_PROMPT_VERSION = 'qa-gate-v1';

const QA_TOOL = {
  name: 'submit_qa_results',
  description: 'Submit QA review results for each candidate item, in the same order they were provided.',
  input_schema: {
    type: 'object',
    properties: {
      results: {
        type: 'array',
        items: {
          type: 'object',
          properties: {
            index: { type: 'integer', description: 'Zero-based index matching the input item order.' },
            qa_status: {
              type: 'string',
              enum: ['VERIFIED', 'QUALIFIED', 'SPECULATIVE', 'NEEDS_REVIEW', 'REJECTED'],
              description: 'QA determination for this item.',
            },
            qa_notes: { type: 'string', description: 'Brief rationale: what was checked, why this status was assigned, any concerns.' },
            claim_type: {
              type: 'string',
              enum: ['signal'],
              description: 'Always "signal" for Grok-sourced items -- never "fact" or "extracted_finding".',
            },
          },
          required: ['index', 'qa_status', 'qa_notes', 'claim_type'],
        },
      },
    },
    required: ['results'],
  },
};

const EXTERNAL_CRITERIA = `
You are a QA reviewer for externally-sourced intelligence gathered by an automated web search tool (Grok).
This tool has NO independent authority -- you are the sole gate between its raw output and anything the
system is allowed to treat as verified.

For each item, you are given: source_url, claim (the extracted assertion), and category.

Evaluate each item against these criteria:
1. SOURCE CREDIBILITY: Is source_url a plausible, identifiable, real-world source (not a placeholder,
   not a search-engine results page, not clearly fabricated)?
2. CLAIM SPECIFICITY: Is the claim a concrete, checkable assertion (not vague speculation, not an opinion
   phrased as fact)?
3. INTERNAL CONSISTENCY: Does the claim make internal sense (no self-contradiction, no obviously
   impossible figures)?
4. NO OVERREACH: The claim must be reported AS STATED by the source -- do not upgrade a hedge, estimate,
   or rumor into a firm fact.

Assign qa_status per item:
- VERIFIED: source is credible and claim is specific, checkable, and consistent. Highest confidence.
- QUALIFIED: source is credible but claim has minor caveats (dated, partial, one-source-only) -- usable
  but should be flagged as qualified.
- NEEDS_REVIEW: source or claim has real ambiguity a human should resolve before this is used for anything.
- REJECTED: source is not credible, claim is fabricated/unverifiable, or claim materially misrepresents
  what a credible source would say.

You may NEVER assign SPECULATIVE to an external intelligence item -- that status is reserved exclusively
for innovation candidates, which are hypotheses, not sourced claims.

claim_type is always "signal". You are labelling external information for a downstream advisor -- you are
not certifying it as EvidenceOS corpus evidence, and you must never phrase qa_notes in a way that implies
it is.
`.trim();

const INNOVATION_CRITERIA = `
You are a QA reviewer for innovation candidates generated by an automated ideation tool (Grok). These are
HYPOTHESES, not findings -- they must never be represented as evidence, verified fact, or extracted from
any real source.

For each item, you are given: idea (the candidate), rationale, and context_summary it was generated from.

Evaluate each item against these criteria:
1. RELEVANCE: Does the idea plausibly relate to the given context (not generic, not off-topic)?
2. COHERENCE: Is the idea internally logical and specific enough to be actionable as a hypothesis
   (not vague filler)?
3. SAFETY/SANITY: Is the idea free of anything harmful, clearly infeasible, or nonsensical?
4. NO FALSE AUTHORITY: The idea/rationale must not be phrased as if it is a documented fact, a cited
   source, or a verified outcome. Reject or flag if it is.

Assign qa_status per item:
- SPECULATIVE: idea is relevant, coherent, and safe. This is the ONLY "accepted" status available for
  innovation candidates -- it is a ceiling, not a floor: even a strong idea remains speculative.
- NEEDS_REVIEW: idea has ambiguity, partial relevance, or borderline safety a human should judge.
- REJECTED: idea is incoherent, unsafe, off-topic, or phrased with false authority.

You may NEVER assign VERIFIED or QUALIFIED to an innovation candidate -- those statuses imply sourced,
checkable fact, which no innovation candidate can ever be, by definition.

claim_type is always "signal". qa_notes must not use language like "confirmed", "proven", or "fact" --
use "plausible", "consistent with context", "worth exploring" instead.
`.trim();

function withTimeout(promise, ms, label) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(`${label} timed out after ${ms} ms`)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

function itemsToPromptText(items, kind) {
  if (kind === 'EXTERNAL') {
    return items.map((it, i) => `[${i}] claim: ${it.claim}\n    source_url: ${it.source_url}\n    category: ${it.category}`).join('\n\n');
  }
  return items.map((it, i) => `[${i}] idea: ${it.idea}\n    rationale: ${it.rationale}\n    context_summary: ${it.context_summary}`).join('\n\n');
}

// Forces every result onto the kind's allowed status set, regardless of
// what the model returned. This is the hard, code-level enforcement of the
// architectural invariant stated in both prompts above -- not merely a
// prompt instruction the model could ignore.
function sanitiseStatus(status, kind) {
  const allowed = kind === 'EXTERNAL' ? EXTERNAL_ALLOWED_STATUSES : INNOVATION_ALLOWED_STATUSES;
  return allowed.includes(status) ? status : 'NEEDS_REVIEW';
}

// Fail-closed placeholder used for every item in a batch when the QA call
// itself fails for any reason (timeout, malformed response, API error) or
// when a specific index is missing from the model's response. Nothing ever
// defaults to an accepted status on failure.
function failClosedResult(index, reason) {
  return {
    index,
    qa_status: 'NEEDS_REVIEW',
    qa_notes: `QA gate unavailable at review time (${reason}); routed to NEEDS_REVIEW pending manual review.`,
    claim_type: 'signal',
  };
}

// Pure assembly step: rebuilds one result per input item, by index, from
// the tool call's raw `results` array. Never spreads or copies a raw result
// wholesale -- only index/qa_status/qa_notes are ever read from it, so an
// unexpected field in a hostile or malformed tool response can never reach
// the returned result. Exported so tests can exercise sanitisation and
// fail-closed-per-missing-index behaviour without a live Anthropic call.
function assembleQaResults(items, kind, rawResults, model, completedAt) {
  const results = Array.isArray(rawResults) ? rawResults : [];
  const byIndex = new Map(results.map(r => [Number(r && r.index), r]));
  return items.map((_, i) => {
    const r = byIndex.get(i);
    if (!r) return { ...failClosedResult(i, 'no result returned for this item'), model, qa_completed_at: completedAt };
    return {
      index: i,
      qa_status: sanitiseStatus(r.qa_status, kind),
      qa_notes: typeof r.qa_notes === 'string' && r.qa_notes ? r.qa_notes : '(no notes provided)',
      claim_type: 'signal',
      model,
      qa_completed_at: completedAt,
    };
  });
}

// A full fail-closed batch: every item gets NEEDS_REVIEW. Used when the
// live call itself fails (timeout, API error, no tool_use block).
function failClosedBatch(items, reason, model) {
  const at = new Date().toISOString();
  return items.map((_, i) => ({ ...failClosedResult(i, reason), model, qa_completed_at: at }));
}

// Runs the QA gate over a batch of raw scout items. kind is 'EXTERNAL' or
// 'INNOVATION'. Returns an array of { index, qa_status, qa_notes,
// claim_type, model, qa_completed_at } aligned 1:1 with `items` by index.
// Never throws -- a total failure yields a NEEDS_REVIEW result for every
// item via failClosedBatch, not an exception the caller must separately
// handle.
async function runQaGate(items, kind) {
  if (!Array.isArray(items) || !items.length) return [];
  if (kind !== 'EXTERNAL' && kind !== 'INNOVATION') {
    throw new Error(`runQaGate: unknown kind "${kind}"`);
  }

  const cfg = agentConfig('qa_gate');
  const criteria = kind === 'EXTERNAL' ? EXTERNAL_CRITERIA : INNOVATION_CRITERIA;
  const prompt = [
    criteria,
    '',
    `Review these ${items.length} item(s) and call submit_qa_results with one result per item, in order:`,
    '',
    itemsToPromptText(items, kind),
  ].join('\n');

  try {
    const work = (async () => {
      const resp = await client.messages.create({
        model: cfg.model,
        max_tokens: cfg.max_tokens,
        tools: [QA_TOOL],
        tool_choice: { type: 'tool', name: 'submit_qa_results' },
        messages: [{ role: 'user', content: prompt }],
      });
      const toolUse = (resp.content || []).find(b => b.type === 'tool_use' && b.name === 'submit_qa_results');
      if (!toolUse) throw new Error('QA gate did not return structured results');
      return { input: toolUse.input || {}, model: resp.model || cfg.model };
    })();

    const { input, model } = await withTimeout(work, cfg.timeout_ms, 'qa_gate');
    const completedAt = new Date().toISOString();
    return assembleQaResults(items, kind, input.results, model, completedAt);
  } catch (err) {
    return failClosedBatch(items, err.message, cfg.model);
  }
}

module.exports = {
  runQaGate,
  assembleQaResults,
  failClosedBatch,
  sanitiseStatus,
  EXTERNAL_ALLOWED_STATUSES,
  INNOVATION_ALLOWED_STATUSES,
  QA_PROMPT_VERSION,
  QA_TOOL,
  EXTERNAL_CRITERIA,
  INNOVATION_CRITERIA,
};
